version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
#      - linux
#      - windows
      - darwin
    goarch:
      - "386"
      - amd64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: yodamad
    name: heimdall
  draft: false
  prerelease: auto
  make_latest: true
  replace_existing_draft: true
  name_template: 'Release v{{ .Tag }}'
  header: |
    ## 🎉 Release v{{ .Tag}} ({{ .Date }})
  footer: |
    ## Enjoy 🍹
    Copyright @yodamad
